global:
  checkNewVersion: true
  sendAnonymousUsage: false

api:
  dashboard: false
  insecure: false

log:
  level: INFO
  format: json

accessLog:
  format: json

entryPoints:
  web:
    address: ":80"

providers:
  file:
    directory: /etc/traefik/dynamic
    watch: true